version: "3.3"

services:
  forgazabot:
    container_name: telegram-bot
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: forgazabot:latest
    restart: always
    env_file:
      - ../.env
